---
version: '3'
services:
  postgresql:
    image: postgres:9.5
    container_name: pixela_db
    environment:
      POSTGRES_USER: pixela
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --no-locale"
      LANG: ja_JP.UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
